### ISSUE TITLE
Password authentication failed, version=3.2.0

### ISSUE THREAD

**Issue by tporto** [django-dbbackup/django-dbbackup#267]
Run command: python manage.py dbbackup

Error: FATAL:  password authentication failed for user "postgres"\nFATAL:  password authentication failed for user "postgres"\n'

Version:
django-dbbackup==3.2.0
django-storages==1.6.5
dropbox==8.4.0

**Comment by ZuluPro** [comment]
Could you guvemore informations ?

**Comment by dmnunez1993** [comment]
Same issue here, I believe $PGPASSWORD is set with quotes, at least in my case, is it possible that I my settings are incorrect?

**Comment by dmnunez1993** [comment]
my settings are:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db',
        'USER': 'user',
        'PASSWORD': 'pwd',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'user',
        'PASSWORD': 'pwd'',
        'HOST': 'localhost'
    }
}

**Comment by bahar** [comment]
I have faced the same problem, then after trying a lot of ways, finally realized it was due to a special character in my pg password. 

Prior to db-backup 3.2.0, it was working alright. I assume something was broken in between.

**Comment by mybigredbutton** [comment]
@bahar is right, this bug gets triggered by special characters in the database password. 

@ZuluPro here is how to reproduce & fix the problem. The problem is when using the function `utils.get_escaped_command_arg()` in the file `postgresql.py`. If your database password has a white space, your password will be enclosed within single or double quotes. Therefore, your password will be changed before trying to establish the connection.

- dbbackup/db/postgresql.py:

<pre>
    def run_command(self, *args, **kwargs):
        if self.settings.get('PASSWORD'):
            env = kwargs.get('env', {})
            env['PGPASSWORD'] = <b>utils.get_escaped_command_arg(</b>self.settings['PASSWORD']<b>)</b> # <-- here is the problem
</pre>

**Comment by ZuluPro** [comment]
@mybigredbutton Thx for the diagnostic !

**Comment by marcelhekking** [comment]
What's the status on this bug. Already fixed?

**Comment by retosteffen** [comment]
I have the same problem. Is there a fix or new version?

**Comment by pawisoon** [comment]
@bahar what characters were causing that trouble? "$" or "%"?

**Comment by pawisoon** [comment]
After changing password to a one that doesn't contain any numbers or special characters like %$# backup works without problems

**Comment by manthanchauhan** [comment]
> @bahar what characters were causing that trouble? "$" or "%"?

@ caused trouble in my case.

**Comment by pawisoon** [comment]
> > @bahar what characters were causing that trouble? "$" or "%"?
> 
> @ caused trouble in my case.

In my case $ and % are causing it. So in version 3.2.0 problem still persists

**Comment by mihow** [comment]
`^` is another character that caused this problem for me. Using version 3.2.0

**Comment by LeeHanYeong** [comment]
`!`is problem, too...

**Comment by jonathan-s** [comment]
@LeeHanYeong, @mihow @pawisoon @manthanchauhan @retosteffen @marcelhekking @bahar. Do you think you could verify if you see this issue in current master?

**Comment by jonathan-s** [comment]
Should be fixed in #361, if you have any issues in current master let me know and we'll sort this out.

**Comment by enzedonline** [comment]
I'm still seeing this issue. 
django-dbbackup==3.3.0

Password contains caps, lowercase, numbers, !, _

**Comment by chrispijo** [comment]
> @rugys I'm on 3.3.0 also, still the same issue. I don't know why this was closed if it was never fixed. Only solution is to use an account with password of only numbers and letters, no special characters.

Also on 3.3.0 and having this issue. As enzedonline mentions, using password without special characters works.

**Comment by SergSm** [comment]
+1 having the same issue with password on 3.3.0

**Comment by SergSm** [comment]
But the way on Mac os the trouble has gone but on my ubuntu 18.04 still persists
