### ISSUE TITLE
Which is USERNAME and PASSWORD should I put no `DBBACKUP_CONNECTORS`?

### ISSUE THREAD

**Issue by rightx2** [django-dbbackup/django-dbbackup#282]
I use PostgreSQL 9.5 and use md5 authentication

I set my system User ID and password on `DBBACKUP_CONNECTORS` settings.
```
DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'rightx2',
        'PASSWORD': 'MY_SYSTEM_PASSWD',
    }
}
```

Whenever I execute command, `python manage.py dbbackup`, it occurred errors:
```
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump super_trading --host=localhost --port=5432 --username=rightx2 --no-password --clean
b'pg_dump: [archiver (db)] connection to database "super_trading" failed: FATAL:  password authentication failed for user "rightx2"\nFATAL:  password authentication failed for user "rightx2"\n'
```

I wonder what I should put on `USER` and `PASSWORD` in  `DBBACKUP_CONNECTORS`

**Comment by ZuluPro** [comment]
Obviously you must set you database password and user in these settings.
But are sure about your settings ? Does it work with your default database settings ?

**Comment by rightx2** [comment]
@ZuluPro If I removed `DBBACKUP_CONNECTORS` part in my `settings` and run `python manage.py dbbackup`, same error occurs,
```
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump super_trading --host=localhost --port=5432 --username=rightx2 --no-password --clean
b'pg_dump: [archiver (db)] connection to database "super_trading" failed: FATAL:  password authentication failed for user "rightx2"\nFATAL:  password authentication failed for user "rightx2"\n'
```

So I have checked whether my database's method of authentication is really `md5` .

My default datbase settings:
```
DATABASES['default'] = dj_database_url.config(
    default="postgres://rightx2:MY_SYSTEM_PASSWD!@localhost:5432/super_trading"
)
```

And I tried to change username from `rightx2` to `asdf` and run `python manage.py makemigrations & migrate`, it occurred errors too,
```

    self.connection = self.get_new_connection(conn_params)
  File "/home/rightx2/.pyenv/versions/super_trading_project/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/rightx2/.pyenv/versions/super_trading_project/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "asdf"
FATAL:  password authentication failed for user "asdf"

Makefile:2: recipe for target 'migrate' failed
make: *** [migrate] Error 1

```
I did the same test for the password, it occurred the same error, too.

According to this, I'm sure that the way of authenticating is `md5`.

But `python manage.py dbbackup` still doesn't work and I don't know why...

**Comment by rightx2** [comment]
Seems like it didn't read `MY_DB_PASSWD` in the `settings` according to `dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump super_trading --host=localhost --port=5432 --username=rightx2 --no-password --clean
`

**Comment by rightx2** [comment]
I think I found a bug. I will pull the request soon

**Comment by pawisoon** [comment]
I'm having the same issue as op

**Comment by cecilurat** [comment]
Can you tell if you solved the problem?

**Comment by cecilurat** [comment]
Resolvi el problema, se tiene que instalar la version anterior de db-backup.

pip uninstall django-dbbackup 
pip install django-dbbackup==3.0

**Comment by Nielssie** [comment]
Had the same problem. 
postgres (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
downgraded from 3.2.0 --> 3.0 
Fixed

**Comment by NoahRR** [comment]
@rightx2 did you ever find a solution to this? I'm getting the same error that you initially put (seems to not be recognizing the password I inputted in DBBACKUP_CONNECTORS)

**Comment by jonathan-s** [comment]
Note to self: https://dba.stackexchange.com/a/243220/132631

**Comment by jonathan-s** [comment]
If you install the package directly from github, this issue should now be resolved.

**Comment by skyl** [comment]
seems like the same problem persists with the latest from pypi, 3.3.0

**Comment by skyl** [comment]
I would like to sponsor but I only use shielded Zcash :D Create a page on free2z.cash and I will send $20 worth. I love django-dbbackup and use it all the time :D
